services:
  postgres: 
    container_name: db
    image: postgres:14.3-alpine3.16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autoservico
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend-postgres
  api:
    image: api-img
    build:
      context: ./
      dockerfile: k8s/mock/Dockerfile
    expose: 
      - 8080
    ports:
      - 8080:8080
    environment:
      POSTGRES_DB: autoservico
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    networks:
      - backend-postgres
    depends_on:
      - postgres
    pull_policy: never
  webhook-mock:
    image: mockoon/cli
    platform: linux/x86_64
    hostname: webhook-mock
    ports:
      - '9999:9999'
    command: -d /data -p 9999
    volumes:
      - ./src/main/resources/mockoon/webhook-mock.json:/data
    networks:
      - backend-postgres

volumes:
  data:
    external: true
networks:
  backend-postgres:
